feat(max zoom): add max zoom option to export
MapColonies/exporter-worker pull request #110
Opened 2020-12-07 14:18 UTC by shimoncohen

2020-12-07 14:54 UTC, asafMasa requested changes

2020-12-07 14:54 UTC, asafMasa commented on src/exportImage.py
> +        resolution = self.__zoom_to_resolution[f'{max_zoom}']
add resolution validation and fail it if missing

2020-12-08 10:28 UTC, asafMasa approved these changes

2020-12-08 10:28 UTC, asafMasa commented on src/exportImage.py
> +        raise Exception(f'No such zoom level. got: {zoom_level}')
make sure the taskId is displayed in log

2020-12-08 10:45 UTC, shimoncohen commented on src/exportImage.py
> +        raise Exception(f'No such zoom level. got: {zoom_level}')
added

2020-12-09 08:20 UTC, merged