feat: add support in s3
MapColonies/exporter-worker pull request #114
Opened 2020-12-22 08:47 UTC by AnguIar

2020-12-22 12:22 UTC, AnguIar commented
- [ ] S3 download links expire after 1 week **at max**, how do we solve this

2020-12-22 16:18 UTC, asafMasa requested changes
🥇 good job

2020-12-22 16:18 UTC, asafMasa commented on confd/production.tmpl
> +        "topic": "{{ getv "/configuration/exporter/worker/kafka/topic" "topic-try-123" }}",
revert and erase the topic

2020-12-22 16:18 UTC, asafMasa commented on confd/production.tmpl
> +    "storage_provider": "{{ getv "/configuration/exporter/worker/storage/provider" "fs" }}",
insert "external_physical_path" and "internal_outputs_path"  under fs {} config object

2020-12-22 16:18 UTC, asafMasa commented on confd/production.tmpl
> +    "storage_provider": "{{ getv "/configuration/exporter/worker/storage/provider" "fs" }}",
rename "input_output" to something meaningful

2020-12-22 16:18 UTC, asafMasa commented on run.sh
> +-e CONFIGURATION_EXPORTER_WORKER_EXPORTSTORAGE_URL=http://192.168.49.1:8080 \
revert

2020-12-22 16:18 UTC, asafMasa commented on confd/production.tmpl
> +    "storage_provider": "{{ getv "/configuration/exporter/worker/storage/provider" "fs" }}",
add "storage_provider" usage to readme file

2020-12-22 16:18 UTC, asafMasa commented on src/exportImage.py
> +
after upload do:
1. get full size // file_size = path.getsize(fullPath)
2.  self.delete_local_directory(directoryName)
3. send to save_update the full_size as an optional parametrer

2020-12-23 08:32 UTC, asafMasa requested changes
![image](https://user-images.githubusercontent.com/18442671/102976234-ef7e8300-4509-11eb-847b-6c97b412f30e.png)
why?

2020-12-23 08:32 UTC, asafMasa commented on README.md
> +when running in production must provide config value: "FS_EXTERNAL_PHYSICAL_PATH" (see below on configurations section) as full path, to declare the creation of the packages location,
must? what if we choose s3?

2020-12-23 08:39 UTC, AnguIar commented
> ![image](https://user-images.githubusercontent.com/18442671/102976234-ef7e8300-4509-11eb-847b-6c97b412f30e.png)
> why?

It says empty file but if you look into it (`view file`) you see that it's all good.

2020-12-23 08:42 UTC, asafMasa approved these changes

2020-12-23 08:42 UTC, asafMasa commented on confd/production.tmpl
> +        "topic": "{{ getv "/configuration/exporter/worker/kafka/topic" "topic-try-123" }}",
revert

2020-12-23 09:09 UTC, merged