chore: added liveness check
MapColonies/exporter-worker pull request #32
Opened 2020-10-04 09:24 UTC by CL-SHLOMIKONCHA

2020-10-04 10:09 UTC, cl-shaharshavit-rnd commented on Dockerfile
> +CMD ["python3", "main..py"]
double dot

2020-10-11 08:37 UTC, asafMasa requested changes

2020-10-11 08:37 UTC, asafMasa commented on src/main.py
> +            probe.readiness = False
liveliness

2020-10-11 08:37 UTC, asafMasa commented on src/main.py
> +            probe.readiness = False
add rediness

2020-10-12 07:30 UTC, CL-SHLOMIKONCHA commented on Dockerfile
> +CMD ["python3", "main..py"]
fixed in 5d9a038

2020-10-12 07:39 UTC, CL-SHLOMIKONCHA commented on src/main.py
> +            probe.readiness = False
fixed in 5d9a038

2020-10-12 07:49 UTC, asafMasa approved these changes

2020-10-12 08:24 UTC, merged